# Created using wingetcreate 1.9.14.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: feraxhp.grp
PackageVersion: 0.7.1
PackageLocale: en-US
Publisher: feraxhp
PackageName: grp
License: MIT License
ShortDescription: A simple CLI tool to mannage platforms for git repositories
ManifestType: defaultLocale
ManifestVersion: 1.9.0
